force-app/main/default/objects/Todo__c/Todo__c.object-meta.xml
<CustomObject>
    <description>Todo item custom object</description>
    <label>Todo</label>
    <nameField>
        <label>Todo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Todos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Todo__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <defaultValue>&quot;Later&quot;</defaultValue>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Today</fullName>
            </value>
            <value>
                <fullName>Tomorrow</fullName>
            </value>
            <value>
                <fullName>Later</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Todo__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <defaultValue>&quot;We need...&quot;</defaultValue>
    <label>Description</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Todo__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <defaultValue>&quot;low&quot;</defaultValue>
    <label>Priority</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>low</fullName>
            </value>
            <value>
                <fullName>medium</fullName>
            </value>
            <value>
                <fullName>high</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Todo__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;draft&quot;</defaultValue>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>draft</fullName>
            </value>
            <value>
                <fullName>in progress</fullName>
            </value>
            <value>
                <fullName>done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TodoController.cls
public with sharing class TodoController {
    @AuraEnabled(Cacheable=true)
    public static Todo__c[] getAllTodos() {
        return [
            SELECT
                Id, 
                Name, 
                Description__c, 
                CreatedDate, 
                Category__c, 
                Priority__c, 
                Status__c 
            FROM Todo__c
            WITH SECURITY_ENFORCED
            ORDER BY Name
            LIMIT 50
        ];
    }

    @AuraEnabled(Cacheable=true)
    public static Todo__c[] searchTodos(String searchTerm, String searchTermDesc) {
        searchTerm = searchTerm.trim();
        searchTermDesc = searchTermDesc.trim();
        String filterSearch;
        filterSearch = searchTerm + searchTermDesc;
        if (filterSearch == '') {
            return getAllTodos();
        }
        String condition = '';
        if(searchTerm!=''){
            searchTerm = '%' + searchTerm + '%';
            condition += ' AND Name LIKE :searchTerm ';
        }
        if(searchTermDesc!=''){
            searchTermDesc = '%' + searchTermDesc + '%';
            condition += ' AND Description__c LIKE :searchTermDesc ';
        }
       
        String query = 
            'SELECT '+ 
                'Id,'+ 
                'Name,'+ 
                'Description__c,'+ 
                'CreatedDate,'+ 
                'Category__c,'+ 
                'Priority__c,'+ 
                'Status__c'+ 
            ' FROM Todo__c'+ 
            ' WHERE Id!=null '+ condition +
            ' WITH SECURITY_ENFORCED'+
            ' ORDER BY Name'+
            ' LIMIT 50';
        List<Todo__c> TODOS = Database.query(query);
        return TODOS;
    }

    @AuraEnabled(Cacheable=true)
    public static Todo__c[] filterTodos(String varCat, String varPrior, String varStat) {
        // Return all recs when no search term
        String filter;
        filter = varCat + varPrior + varStat;
        if (filter == '') {
            return getAllTodos();
        }
        String condition = '';
        if(varCat!=''){
            condition += ' AND Category__c =:varCat ';
        }
        if(varPrior!=''){
            condition += ' AND Priority__c =:varPrior ';
        }
        if(varStat!=''){
            condition += ' AND Status__c =:varStat ';
        }
        String query = 
            'SELECT '+ 
                'Id,'+ 
                'Name,'+ 
                'Description__c,'+ 
                'CreatedDate,'+ 
                'Category__c,'+ 
                'Priority__c,'+ 
                'Status__c'+ 
            ' FROM Todo__c'+ 
            ' WHERE Id!=null '+ condition +
            ' WITH SECURITY_ENFORCED'+
            ' ORDER BY Name'+
            ' LIMIT 50';
        List<Todo__c> TODOS = Database.query(query);
        return TODOS;
    }
}