force-app/main/default/objects/Contact/fields/Is_Synced__c.field-meta.xml
<CustomField>
    <fullName>Is_Synced__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Synced</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Processed_By_Queue__c.field-meta.xml
<CustomField>
    <fullName>Processed_By_Queue__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Processed By Queue</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/QueueableContactUpdate.cls
public class QueueableContactUpdate implements Queueable {
	List<Id> accountIds;

    public QueueableContactUpdate(List<Id> accountIds) {
        this.accountIds = accountIds;
    }
    public void execute(QueueableContext context) {
		List<Contact> contactsToUpdate = new List<Contact>();  
        List<Account> accounts = [Select Id, Name, (Select Id, FirstName, LastName  FROM Contacts) from Account Where Id IN :accountIds];
        
        for(Account acc: accounts){
            List<Contact> contactList = acc.Contacts;
            contactsToUpdate.addAll(contactList);
            System.debug('List of contacts: '+contactList);
        }
            for(Contact c: contactsToUpdate){
                c.Is_Synced__c = False;
                c.Processed_By_Queue__c = True;
                System.debug('Contact '+c.FirstName+' '+c.LastName+' updated');
            }
        update contactsToUpdate;
    }
}