force-app/main/default/objects/Contact/fields/Is_Synced__c.field-meta.xml
<CustomField>
    <fullName>Is_Synced__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Synced</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Processed_By_Furure__c.field-meta.xml
<CustomField>
    <fullName>Processed_By_Furure__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Processed By Furure</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Processed_By_Queue__c.field-meta.xml
<CustomField>
    <fullName>Processed_By_Queue__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Processed By Queue</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/noTrigger_Queueable.cls
public class noTrigger_Queueable implements Queueable {
	List<Id> accountIds;

    public noTrigger_Queueable(List<Id> accountIds) {
        this.accountIds = accountIds;
    }
    public void execute(QueueableContext context) {
		List<Account> accounts = [Select Id, Name, BillingStreet, BillingCity, BillingState, BillingPostalCode, BillingCountry, BillingLatitude, BillingLongitude, BillingGeocodeAccuracy, (Select Id, FirstName, LastName, Is_Synced__c, Processed_By_Furure__c FROM Contacts) from Account Where Id IN :accountIds LIMIT 150]; 
       List<Contact> contactsToUpdate = new List<Contact>();
        for(Account acc: accounts){
            List<Contact> contacts = acc.Contacts;
            if(acc.BillingCity != null ||
                acc.BillingCountry!= null ||
              	 acc.BillingPostalCode != null ||
              	  acc.BillingState!= null ||
               acc.BillingStreet!= null){
                   
              for(Contact con: contacts){          

                  con.Is_Synced__c = false;
                  con.Processed_By_Queue__c = true;
    
                  contactsToUpdate.add(con);      
                  System.debug('Contact '+con.FirstName+' '+con.LastName+' updated');
                	}   
               }
          } 
        
        if(contactsToUpdate.size() > 0){
        update contactsToUpdate;
        }
	}
}